version: "3.8"
services:
  web:
    build:
      context: ./Frontend
    ports:
      - "4000:4000"
    volumes:
      - ${PROJECT_PATH}/Frontend:/app
      - ${PROJECT_PATH}/Frontend/node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start
